### ISSUE TITLE
Issue with Substrate v1.0 with the GenesisConfig

### ISSUE THREAD

**Issue by Noc2** [substrate-developer-hub/substrate-tcr#3]
The runtime doesn’t work with the current Substrate version v1.0 (at least on my pc) because of the following issue:
https://github.com/paritytech/substrate/pull/2585. The issue is already resolved if you update the runtime to the current master branch.

**Comment by gautamdhameja** [comment]
Thanks for reporting this. I'm in the process of updating this sample to the latest compatible Substrate codebase.

**Comment by gautamdhameja** [comment]
The code is now upgraded to work with Substrate v1.0 branch. Closing this issue.
